name: Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Testing
        run: Get-Module Pester -ListAvailable
        shell: pwsh